export const REQUEST_STATUSES = Object.freeze({
  OPEN: "OPEN",
  ACCEPTED: "ACCEPTED",
  IN_PROGRESS: "IN_PROGRESS",
  AWAITING_CONFIRMATION: "AWAITING_CONFIRMATION",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
  FAILED: "FAILED",
});

export const REQUEST_STATUS_LABELS = Object.freeze({
  [REQUEST_STATUSES.OPEN]: "Open",
  [REQUEST_STATUSES.ACCEPTED]: "Accepted",
  [REQUEST_STATUSES.IN_PROGRESS]: "In progress",
  [REQUEST_STATUSES.AWAITING_CONFIRMATION]: "Awaiting confirmation",
  [REQUEST_STATUSES.COMPLETED]: "Completed",
  [REQUEST_STATUSES.CANCELLED]: "Cancelled",
  [REQUEST_STATUSES.FAILED]: "Delivery failed",
});

export const REQUEST_STATUS_TRANSITIONS = Object.freeze({
  [REQUEST_STATUSES.OPEN]: [REQUEST_STATUSES.ACCEPTED, REQUEST_STATUSES.CANCELLED],
  [REQUEST_STATUSES.ACCEPTED]: [
    REQUEST_STATUSES.OPEN,
    REQUEST_STATUSES.IN_PROGRESS,
    REQUEST_STATUSES.CANCELLED,
  ],
  [REQUEST_STATUSES.IN_PROGRESS]: [
    REQUEST_STATUSES.AWAITING_CONFIRMATION,
    REQUEST_STATUSES.FAILED,
  ],
  [REQUEST_STATUSES.AWAITING_CONFIRMATION]: [REQUEST_STATUSES.COMPLETED],
  [REQUEST_STATUSES.COMPLETED]: [],
  [REQUEST_STATUSES.CANCELLED]: [],
  [REQUEST_STATUSES.FAILED]: [],
});

export const FULFILLMENT_TYPES = Object.freeze({
  PICKUP_ONLY: "pickup_only",
  DELIVERY: "delivery",
  PURCHASE_AND_DELIVER: "purchase_and_deliver",
  ON_SITE: "on_site",
});

export const FULFILLMENT_TYPE_LABELS = Object.freeze({
  [FULFILLMENT_TYPES.PICKUP_ONLY]: "Pickup only",
  [FULFILLMENT_TYPES.DELIVERY]: "Pickup and delivery",
  [FULFILLMENT_TYPES.PURCHASE_AND_DELIVER]: "Purchase and deliver",
  [FULFILLMENT_TYPES.ON_SITE]: "On-site errand",
});

export const PAYMENT_ARRANGEMENTS = Object.freeze({
  NO_PURCHASE: "NO_PURCHASE",
  MERCHANT_PREPAID: "MERCHANT_PREPAID",
  RUNNER_ADVANCE: "RUNNER_ADVANCE",
});

export const PAYMENT_ARRANGEMENT_LABELS = Object.freeze({
  [PAYMENT_ARRANGEMENTS.NO_PURCHASE]: "No purchase expense",
  [PAYMENT_ARRANGEMENTS.MERCHANT_PREPAID]: "Merchant already paid",
  [PAYMENT_ARRANGEMENTS.RUNNER_ADVANCE]: "Runner cash advance",
});

export const PAYMENT_PAYER_TYPES = Object.freeze({
  REQUESTOR: "REQUESTOR",
  RECIPIENT: "RECIPIENT",
});

export const PAYMENT_PAYER_LABELS = Object.freeze({
  [PAYMENT_PAYER_TYPES.REQUESTOR]: "Requestor pays the Runner",
  [PAYMENT_PAYER_TYPES.RECIPIENT]: "Recipient pays the Runner",
});

export const PRICE_CHANGE_STATUSES = Object.freeze({
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  DECLINED: "DECLINED",
  WITHDRAWN: "WITHDRAWN",
});

export const PRICE_CHANGE_STATUS_LABELS = Object.freeze({
  [PRICE_CHANGE_STATUSES.PENDING]: "Waiting for Requestor",
  [PRICE_CHANGE_STATUSES.APPROVED]: "Approved",
  [PRICE_CHANGE_STATUSES.DECLINED]: "Declined",
  [PRICE_CHANGE_STATUSES.WITHDRAWN]: "Withdrawn",
});

export const FAILURE_REASONS = Object.freeze({
  RECIPIENT_UNAVAILABLE: "RECIPIENT_UNAVAILABLE",
  WRONG_OR_INACCESSIBLE_ADDRESS: "WRONG_OR_INACCESSIBLE_ADDRESS",
  PAYMENT_REFUSED: "PAYMENT_REFUSED",
  ITEM_REJECTED: "ITEM_REJECTED",
  UNSAFE_SITUATION: "UNSAFE_SITUATION",
  OTHER: "OTHER",
});

export const FAILURE_REASON_LABELS = Object.freeze({
  [FAILURE_REASONS.RECIPIENT_UNAVAILABLE]: "Recipient unavailable",
  [FAILURE_REASONS.WRONG_OR_INACCESSIBLE_ADDRESS]:
    "Wrong or inaccessible address",
  [FAILURE_REASONS.PAYMENT_REFUSED]: "Payment refused",
  [FAILURE_REASONS.ITEM_REJECTED]: "Item or delivery rejected",
  [FAILURE_REASONS.UNSAFE_SITUATION]: "Unsafe situation",
  [FAILURE_REASONS.OTHER]: "Other reason",
});

export const DISPUTE_CATEGORIES = Object.freeze({
  ITEM_OR_SERVICE: "ITEM_OR_SERVICE",
  PAYMENT: "PAYMENT",
  NO_SHOW: "NO_SHOW",
  SAFETY: "SAFETY",
  OTHER: "OTHER",
});

export const DISPUTE_CATEGORY_LABELS = Object.freeze({
  [DISPUTE_CATEGORIES.ITEM_OR_SERVICE]: "Item or service problem",
  [DISPUTE_CATEGORIES.PAYMENT]: "Payment problem",
  [DISPUTE_CATEGORIES.NO_SHOW]: "No-show",
  [DISPUTE_CATEGORIES.SAFETY]: "Safety concern",
  [DISPUTE_CATEGORIES.OTHER]: "Other issue",
});

export const DISPUTE_STATUS_LABELS = Object.freeze({
  OPEN: "Open — awaiting review",
  WITHDRAWN: "Withdrawn",
  RESOLVED: "Resolved",
  DISMISSED: "Dismissed",
});

export const ACCOUNT_REPORT_CATEGORIES = Object.freeze({
  HARASSMENT: "HARASSMENT",
  SPAM: "SPAM",
  IMPERSONATION: "IMPERSONATION",
  UNSAFE_BEHAVIOR: "UNSAFE_BEHAVIOR",
  OTHER: "OTHER",
});

export const ACCOUNT_REPORT_CATEGORY_LABELS = Object.freeze({
  [ACCOUNT_REPORT_CATEGORIES.HARASSMENT]: "Harassment or threats",
  [ACCOUNT_REPORT_CATEGORIES.SPAM]: "Spam or fake activity",
  [ACCOUNT_REPORT_CATEGORIES.IMPERSONATION]: "Impersonation",
  [ACCOUNT_REPORT_CATEGORIES.UNSAFE_BEHAVIOR]: "Unsafe behavior",
  [ACCOUNT_REPORT_CATEGORIES.OTHER]: "Other safety concern",
});

export const ACCOUNT_REPORT_STATUS_LABELS = Object.freeze({
  OPEN: "Open - awaiting review",
  ACTIONED: "Action taken",
  DISMISSED: "Dismissed",
});
