export const REQUEST_STATUSES = Object.freeze({
  OPEN: "OPEN",
  ACCEPTED: "ACCEPTED",
  IN_PROGRESS: "IN_PROGRESS",
  AWAITING_CONFIRMATION: "AWAITING_CONFIRMATION",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
});

export const REQUEST_STATUS_LABELS = Object.freeze({
  [REQUEST_STATUSES.OPEN]: "Open",
  [REQUEST_STATUSES.ACCEPTED]: "Accepted",
  [REQUEST_STATUSES.IN_PROGRESS]: "In progress",
  [REQUEST_STATUSES.AWAITING_CONFIRMATION]: "Awaiting confirmation",
  [REQUEST_STATUSES.COMPLETED]: "Completed",
  [REQUEST_STATUSES.CANCELLED]: "Cancelled",
});

export const REQUEST_STATUS_TRANSITIONS = Object.freeze({
  [REQUEST_STATUSES.OPEN]: [REQUEST_STATUSES.ACCEPTED, REQUEST_STATUSES.CANCELLED],
  [REQUEST_STATUSES.ACCEPTED]: [
    REQUEST_STATUSES.OPEN,
    REQUEST_STATUSES.IN_PROGRESS,
    REQUEST_STATUSES.CANCELLED,
  ],
  [REQUEST_STATUSES.IN_PROGRESS]: [REQUEST_STATUSES.AWAITING_CONFIRMATION],
  [REQUEST_STATUSES.AWAITING_CONFIRMATION]: [REQUEST_STATUSES.COMPLETED],
  [REQUEST_STATUSES.COMPLETED]: [],
  [REQUEST_STATUSES.CANCELLED]: [],
});

export const FULFILLMENT_TYPES = Object.freeze({
  PICKUP_ONLY: "pickup_only",
  DELIVERY: "delivery",
  PURCHASE_AND_DELIVER: "purchase_and_deliver",
  ON_SITE: "on_site",
});

export const FULFILLMENT_TYPE_LABELS = Object.freeze({
  [FULFILLMENT_TYPES.PICKUP_ONLY]: "Pickup only",
  [FULFILLMENT_TYPES.DELIVERY]: "Pickup and delivery",
  [FULFILLMENT_TYPES.PURCHASE_AND_DELIVER]: "Purchase and deliver",
  [FULFILLMENT_TYPES.ON_SITE]: "On-site errand",
});
